// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ZooApi.Data;

#nullable disable

namespace ZooApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260404231319_InitializeSeedData")]
    partial class InitializeSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ZooApi.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<string>("Feeding")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Health")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Count = 5,
                            Feeding = "5:00 PM",
                            Gender = "Male",
                            Health = "Healthy",
                            Image = "/images/elephant.png",
                            Latitude = 45.5,
                            Longitude = -90.700000000000003,
                            Name = "Henri",
                            Species = "Elephant",
                            Status = "Open"
                        },
                        new
                        {
                            Id = 2,
                            Count = 8,
                            Feeding = "8:00 PM",
                            Gender = "Female",
                            Health = "Healthy",
                            Image = "/images/tiger.png",
                            Latitude = 44.5,
                            Longitude = -91.200000000000003,
                            Name = "Aurora",
                            Species = "Tiger",
                            Status = "Open"
                        },
                        new
                        {
                            Id = 3,
                            Count = 4,
                            Feeding = "12:00 PM",
                            Gender = "Male",
                            Health = "Healthy",
                            Image = "/images/panda.png",
                            Latitude = 43.5,
                            Longitude = -89.599999999999994,
                            Name = "Cliff",
                            Species = "Panda",
                            Status = "Open"
                        },
                        new
                        {
                            Id = 4,
                            Count = 7,
                            Feeding = "9:00 PM",
                            Gender = "Male",
                            Health = "Sick",
                            Image = "/images/monkey.png",
                            Latitude = 40.5,
                            Longitude = -90.299999999999997,
                            Name = "Caesar",
                            Species = "Monkey",
                            Status = "Open"
                        });
                });

            modelBuilder.Entity("ZooApi.Models.Visitor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Visitors");
                });

            modelBuilder.Entity("ZooApi.Models.ZooStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ZooStatuses");
                });
#pragma warning restore 612, 618
        }
    }
}
